### ISSUE TITLE
세트

### ISSUE THREAD

**Issue by 00xmanuser** [kimjunsung04/classcard_auto#10]
![스크린샷 2023-11-09 185509](https://github.com/kimjunsung04/classcard_auto/assets/150338593/f3138a3c-0b6e-47f8-bc58-8ca81200c231)
'나의 클래스'  말고 '나의 폴더'에 있는 세트들이 떠요

**Comment by kimjunseong04** [comment]
https://github.com/kimjunsung04/classcard_auto/commit/d16a9e18b5b390509fed0df99336941ae28aa1a7 해당 커밋에서 수정되었습니다.
