### ISSUE TITLE
테스트 튕김현상

### ISSUE THREAD

**Issue by 00xmanuser** [kimjunsung04/classcard_auto#11]
![스크린샷 2023-11-09 200553](https://github.com/kimjunsung04/classcard_auto/assets/150338593/7dc26e2d-9758-4d48-9fc0-436e151f4f2d)
암기, 리콜, 스펠 은 정상 작동하는데 테스트만 누르면 저런게 뜨면서 바로 튕겨요

**Comment by kimjunseong04** [comment]
4d1d86402d8ba185c9cd115e0ad1e2b00acb278f 커밋에서 수정되었습니다! 감사합니다!
