### ISSUE TITLE
테스트/매칭 관련 문제

### ISSUE THREAD

**Issue by sw08** [kimjunsung04/classcard_auto#8]
1. 단어가 분명히 있음에도 불구하고 학습되지 않은 단어라며 랜덤선택 시도. (약 300카드 분량)
2. 현재 클래스카드의 테스트는 6지선다임에도 랜덤 기능은 4지선다인것으로 확인.
3. 테스트, 매칭의 경우 로그인 후 바로 세트로 들어가는 것이 아닌 클래스 접속 후 클래스의 세트 목록에서 골라서 접속해야 함

저로써는 일단 이 정도가 확인되었습니다.

**Comment by kimjunseong04** [comment]
https://github.com/kimjunsung04/classcard_auto/commit/39786398a3f968ccc900510f90b4c7d8937406ab 에서 해결되었습니다.
