### ISSUE TITLE
테스트 학습 관련 문제

### ISSUE THREAD

**Issue by saesac** [kimjunsung04/classcard_auto#9]
현 코드로 테스트 학습을 진행하려고 하면 205번째 줄에서 에러가 납니다.
저만 그런건진 모르겠지만 확인 부탁드립니다.
![image](https://user-images.githubusercontent.com/70804762/158324002-087109a3-ffb2-421d-9dc3-45ba48480891.png)

**Comment by kimjunseong04** [comment]
https://github.com/kimjunsung04/classcard_auto/commit/39786398a3f968ccc900510f90b4c7d8937406ab 에서 해결되었습니다.
